### ISSUE TITLE
Shutdown/Restart

### ISSUE THREAD

**Issue by restlessnap** [tranquilitysmile/asrock-b550-phantom-gaming-itx-ax-opencore#3]
First of all thank you so much for uploading! Your EFI works nearly perfect for me. The only issues I have are with shutdown/restart. If i shutdown it doesnt shutdown all the way and i need to do a full psu drain and power cycle to boot back up. Did you run into this issue as well? 

Is it USB related? Thanks in advance

**Comment by tranquilitysmile** [comment]
Hi, @restlessnap! I think you should check all settings related to usb wakeup in bios.
As for me I have not encountered this problem, i think it depends on the bios settings

**Comment by e-tho** [comment]
~I'm coming in late but these boot/sleep issues are RTC related, check out this [guide](https://dortania.github.io/OpenCore-Post-Install/misc/rtc.html) to find the right value for you, in my case the bad region is `0809` but this could differ depending on BIOS version. 
This may save some time in research for people going through this.~

I was completely wrong, it was actually due to the LED Controller I had mapped to type 255 (proprietary connector). Removing the mapping for this connector fixed the sleep/shutdown issues.
